---
title: "Turnover plot"
author: 
- name: Stephanie Hereira
  affiliation: Centro de Investigación y estudios avanzados del IPN
  email: shereirap@cinvestav.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
---

Loading files
```{r, message=FALSE, warning=FALSE}
library(tidyverse)
intra_ro_wet_q0<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=0-table_wet_ro.txt.csv") %>% mutate(
    qs="q0") %>% mutate(type="wet")
intra_ro_wet_q1<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=1-table_wet_ro.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="wet")
intra_ro_wet_q2<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=2-table_wet_ro.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="wet")

intra_ri_wet_q0<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=0-table_wet_ri.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="wet")
intra_ri_wet_q1<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=1-table_wet_ri.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="wet")
intra_ri_wet_q2<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=2-table_wet_ri.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="wet")

intra_nr_wet_q0<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=0-table_wet_nr.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="wet")
intra_nr_wet_q1<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=1-table_wet_nr.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="wet")
intra_nr_wet_q2<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=2-table_wet_nr.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="wet")


intra_ro_dry_q0<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=0-table_dry_ro.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="dry")
intra_ro_dry_q1<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=1-table_dry_ro.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="dry")
intra_ro_dry_q2<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=2-table_dry_ro.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="dry")

intra_ri_dry_q0<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=0-table_dry_ri.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="dry")
intra_ri_dry_q1<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=1-table_dry_ri.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="dry")
intra_ri_dry_q2<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=2-table_dry_ri.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="dry")

intra_nr_dry_q0<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=0-table_dry_nr.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="dry")
intra_nr_dry_q1<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=1-table_dry_nr.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="dry")
intra_nr_dry_q2<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=2-table_dry_nr.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="dry")


intra_ro_exdry_q0<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=0-table_exdry_ro.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="extreme-dry")
intra_ro_exdry_q1<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=1-table_exdry_ro.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="extreme-dry")
intra_ro_exdry_q2<- read.csv(
  "../Data/beta/Beta_diversityro/Intra_Beta_Similarity-q=2-table_exdry_ro.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="extreme-dry")

intra_ri_exdry_q0<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=0-table_exdry_ri.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="extreme-dry")
intra_ri_exdry_q1<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=1-table_exdry_ri.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="extreme-dry")
intra_ri_exdry_q2<- read.csv(
  "../Data/beta/Beta_diversityri/Intra_Beta_Similarity-q=2-table_exdry_ri.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="extreme-dry")

intra_nr_exdry_q0<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=0-table_exdry_nr.txt.csv") %>% mutate(
    qs="q0")%>% mutate(type="extreme-dry")
intra_nr_exdry_q1<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=1-table_exdry_nr.txt.csv") %>% mutate(
    qs="q1")%>% mutate(type="extreme-dry")
intra_nr_exdry_q2<- read.csv(
  "../Data/beta/Beta_diversitynr/Intra_Beta_Similarity-q=2-table_exdry_nr.txt.csv") %>% mutate(
    qs="q2")%>% mutate(type="extreme-dry")
```

Plot

```{r, warning=FALSE, message=FALSE, fig.height=10}
library(ggpubr)
my_comparisons <- list( c("wet", "dry"), c("wet", "extreme-dry"), c("dry", "extreme-dry") )


intra_ro<- rbind(intra_ro_wet_q0, intra_ro_dry_q0, intra_ro_exdry_q0,
                 intra_ro_wet_q1, intra_ro_dry_q1, intra_ro_exdry_q1,
                 intra_ro_wet_q2, intra_ro_dry_q2, intra_ro_exdry_q2)

i1<-intra_ro %>%mutate(TurnOver= 1-TurnoverComp) %>%  ggpubr::ggboxplot(
  x = "type", y="TurnOver", fill = "type")+
  facet_wrap( ~qs, scales = "free")+xlab("")+
  ylab("Ratio of ASVs turnover-Roots")+
  scale_fill_manual(values = c("DarkGreen", "yellow", "red"))+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
  theme_bw()+
  theme(panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(),
        panel.border = element_rect(color = "black"), 
        panel.spacing.x = unit(0,"line"), 
        axis.line= element_line(colour = "black"), 
        axis.line.y.right = element_line(colour = "black" ),
        axis.text = element_text(colour = "black", size = 10))

intra_ri<- rbind(intra_ri_wet_q0, intra_ri_dry_q0, intra_ri_exdry_q0,
                 intra_ri_wet_q1, intra_ri_dry_q1, intra_ri_exdry_q1,
                 intra_ri_wet_q2, intra_ri_dry_q2, intra_ri_exdry_q2)

i2<-intra_ri %>%mutate(TurnOver= 1-TurnoverComp)%>% ggpubr::ggboxplot(
  x = "type", y="TurnOver", fill = "type")+
  facet_wrap(~qs, scales = "free")+
  xlab("")+ylab("Ratio of ASVs turnover-Rhizosphere")+
  scale_fill_manual(values = c("DarkGreen", "yellow", "red"))+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
  theme_bw()+theme(panel.grid.major = element_blank(), 
                   panel.grid.minor = element_blank(),
                   panel.background = element_blank(),
                   panel.border = element_rect(color = "black"), 
                   panel.spacing.x = unit(0,"line"), 
        axis.line= element_line(colour = "black"), 
        axis.line.y.right = element_line(colour = "black" ),
        axis.text = element_text(colour = "black", size = 10))

intra_nr<- rbind(intra_nr_wet_q0, intra_nr_dry_q0, intra_nr_exdry_q0,
                 intra_nr_wet_q1, intra_nr_dry_q1, intra_nr_exdry_q1,
                 intra_nr_wet_q2, intra_nr_dry_q2, intra_nr_exdry_q2)

i3<-intra_nr%>%mutate(TurnOver= 1-TurnoverComp) %>% ggpubr::ggboxplot(
  x = "type", y="TurnoverComp", fill = "type")+
  facet_wrap(~qs, scales = "free")+xlab("")+
  ylab("Ratio of ASVs turnover-Bulk soil")+
  scale_fill_manual(values = c("DarkGreen", "yellow", "red"))+
  stat_compare_means(comparisons = my_comparisons, label = "p.signif")+
  theme_bw()+theme( panel.grid.major = element_blank(), 
                    panel.grid.minor = element_blank(),   
                    panel.background = element_blank(),
        panel.border = element_rect(color = "black"),
        panel.spacing.x = unit(0,"line"), 
        axis.line= element_line(colour = "black"), 
        axis.line.y.right = element_line(colour = "black" ),
        axis.text = element_text(colour = "black", size = 10))


library(cowplot)
p<-plot_grid(
  i1+theme(legend.position = "none"),i2+theme(legend.position = "none"),
  i3+theme(legend.position = "none"), nrow = 3, labels = c("A", "B", "C"))
p
#ggsave(plot=p, "Figures_final/Fig2.intra-turnover-paired.pdf", width = 10, height = 13)


```

