---
title: "Aldex analysis and heatmap"
author: 
- name: Stephanie Hereira
  affiliation: Centro de Investigación y estudios avanzados del IPN
  email: shereirap@cinvestav.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
---

Aldex analysis

```{r, warning=FALSE, message=FALSE}
#Loading libraries
library(dplyr)
library(stringr)
library(purrr)
library(tidyverse)
library(tibble)
library(tidyr)
library(qiime2R)
library(ALDEx2)
library(tidyverse)
library(ComplexHeatmap)
library(viridis)
library(circlize)
library(RColorBrewer)
library(cowplot)
library(tidyverse)
library(qiime2R)
library(cowplot)
require(compositions) 
require(zCompositions) 
library(ggrepel)
library(vegan)
library(ggpubr)
library(RVAideMemoire)

relabunda<- function(x){(t(t(x)/colSums(x)))*100}

```

```{r, eval=FALSE, warning=FALSE, message=FALSE}
#Importing data
table_240<- read_qza("../../Data/grouped_240_fil_noplant_nous.qza")$data
metadata<- read_tsv("../Data/FINALMAP_GROUPED.txt")
table_240<- table_240 %>% t() %>% data.frame(
  .,check.names = F) %>% rownames_to_column(
    var = "#SampleID") %>% inner_join(
  metadata) %>% arrange(Type_of_soil) %>% dplyr::select(
    -Type_of_soil:-Month) %>% column_to_rownames(
      var = "#SampleID") %>% t() %>% as.data.frame()
table_240_t<- table_240 %>% t()
taxonomy_240<- read_qza("../Data/taxonomy_blast_240_0.97.qza")$data

#remove non-fungi taxa

taxonomy_filter<- taxonomy_240 %>% filter(
  !str_detect(Taxon, "ozoa"))%>% filter(
  !str_detect(Taxon, "helida")) %>% filter(
  !str_detect(Taxon, "ophyta")) %>% filter(
  !str_detect(Taxon, "Ciliophora")) %>% filter(
  !str_detect(Taxon, "Nucleariidae_and_Fonticula_group")) %>% filter(
  !str_detect(Taxon, "Arthrioida")) %>% filter(
  !str_detect(Taxon, "Labyrinthulomycetes"))  %>% filter(
  !str_detect(Taxon, "Apicomplexa")) %>% filter(
  !str_detect(Taxon, "Bicosoecida")) %>% filter(
  !str_detect(Taxon, "Breviatea")) %>% filter(
  !str_detect(Taxon, "Aphelidea"))  %>% filter(
  !str_detect(Taxon, "Arthropoda")) 

table_filter<-  table_240[match(taxonomy_filter$Feature.ID,
                                rownames(table_240)),] %>% drop_na(.)

  
#by taxonomic levels
parse_taxa_240<- parse_taxonomy(taxonomy_filter)

summarize_taxa_240<-summarize_taxa(table_filter,
                                   parse_taxa_240)
Phylum_240<- summarize_taxa_240$Phylum 
Class_240<- summarize_taxa_240$Class
Genus_240<- summarize_taxa_240$Genus

#analysis kruskal wallis all levels
conds<- c(rep("NR", 9), rep("RI", 9), rep("RO", 9))

#avss
aldex_analysis<- aldex.clr(table_filter,
                           mc.samples = 1000, denom="all", verbose = TRUE, conds )

differentials <- aldex.kw(aldex_analysis,  useMC = F, verbose = F)
aldex_240<- differentials %>% rownames_to_column(
  var = "Feature.ID") %>% left_join(taxonomy_240)%>% filter(kw.eBH < 0.05)


#taxonomic levels
aldex_list<- list(Phylum_240, Class_240, Genus_240)


aldex_analysis_function<-function(x){ aldex.clr(x,
mc.samples = 1000, denom="all", verbose = TRUE, conds)}

aldex_analysis<- lapply(aldex_list, aldex_analysis_function)
    
differentials_function <- function(x){aldex.kw(x,  useMC = F, verbose = F)}

differentials_tables_class <- lapply(aldex_analysis, differentials_function)


aldex_phylum<- differentials_tables_class[[1]] %>% rownames_to_column(
  var = "Feature.ID")  %>% filter(kw.eBH<0.05)
aldex_class<- differentials_tables_class[[2]] %>% rownames_to_column(
  var = "Feature.ID")  %>% filter(kw.eBH<0.05)
aldex_genus<- differentials_tables_class[[3]] %>% rownames_to_column(
  var = "Feature.ID")  %>% filter(kw.eBH<0.05)


#Paired test just with asv's
table_240_t<- table_filter %>% t()
otutable1<- data.frame(t(table_240_t),
                       check.names = F, stringsAsFactors = F) %>% dplyr::select_at(
                         vars(contains("Roots")))
otutable2<- data.frame(t(table_240_t), 
                       check.names = F, stringsAsFactors = F) %>% dplyr::select_at(
                         vars(starts_with("Ri")))
otutable3<- cbind(otutable1, otutable2)

otutable4<- data.frame(t(table_240_t), 
                       check.names = F, stringsAsFactors = F) %>% dplyr::select_at(
                         vars(contains("Roots")))
otutable5<- data.frame(t(table_240_t), 
                       check.names = F, stringsAsFactors = F) %>% dplyr::select_at(
                         vars(starts_with("N")))
otutable6<- cbind(otutable4, otutable5)

otutable7<- data.frame(t(table_240_t),
                       check.names = F, stringsAsFactors = F)%>%dplyr::select_at(
                         vars(contains("Non")))
otutable8<- data.frame(t(table_240_t),
                       check.names = F, stringsAsFactors = F) %>% dplyr::select_at(
                         vars(starts_with("Ri")))
otutable9<- cbind(otutable7, otutable8)

conds<- c(rep("A", 9), rep("B", 9))

aldex_list_paired<- list(otutable3, otutable6, otutable9)


aldex_analysis_function_paired<-function(x){ aldex(x,
     mc.samples = 1000, denom="all", verbose = TRUE, conds,  effect = T, test = "t")}

aldex_analysis_paired<- lapply(aldex_list_paired, aldex_analysis_function_paired)


aldex_ro_ri<-aldex_analysis_paired[[1]] %>% rownames_to_column(
  var = "Feature.ID")  %>% filter(wi.eBH < 0.05) %>% left_join(taxonomy_filter)
aldex_ro_nr<- aldex_analysis_paired[[2]] %>% rownames_to_column(
  var = "Feature.ID")  %>% filter(wi.eBH < 0.05) %>% left_join(taxonomy_filter)
aldex_nr_ri<- aldex_analysis_paired[[3]] %>% rownames_to_column(
  var = "Feature.ID")  %>% filter(wi.eBH < 0.05) %>% left_join(taxonomy_filter)


#write.table(aldex_nr_ri,"dif_aldex_nr_ri.tsv", sep = "\t", row.names = T) 

#Aldex for functional predictions of Picrust2

EC_predicted <- read.delim("../Data/pathways_table_all.txt",  
                           check.names = F) %>% dplyr::select(
                             -"#OTU ID") %>% column_to_rownames(
                               var = "taxonomy")

Alpha.t_asv_table<- read.delim("../Data/alpha_all.tsv")


table<- EC_predicted %>% t() %>% as.data.frame() %>% rownames_to_column(
  var = "sampleid")
table_meta<- table %>% inner_join(Alpha.t_asv_table) %>% group_by(
  Type, Treatment, Plot) %>% summarise_if(is.numeric, sum) %>% unite(
    "ids",Type:Plot,  sep = "_") %>% column_to_rownames(
      var = "ids") %>% dplyr::select(-Loc:-value) %>% t() %>% 
  as.data.frame() %>% mutate_if(
      is.numeric, as.integer)

table_nr<- table_meta %>% dplyr::select_at(vars(contains("Bulk")))
table_ri<- table_meta %>% dplyr::select_at(vars(contains("Rhizosphere")))
table_ro<- table_meta %>% dplyr::select_at(vars(contains("Root")))

table_nr_ri<- cbind(table_nr, table_ri)
table_nr_ro<- cbind(table_nr, table_ro)
table_ro_ri<- cbind(table_ro, table_ri)

conds1<- c(rep("bs", 9), rep("ri", 9))
conds2<- c(rep("bs", 9), rep("ro", 9))
conds3<- c(rep("ro", 9), rep("ri", 9))

library(ALDEx2)
aldex_nr_ri<-aldex(table_nr_ri, conditions = conds1, mc.samples = 1000,
                   test = "t", effect = T, denom = "all")
aldex_nr_ro<-aldex(table_nr_ro, conditions = conds2, mc.samples = 1000,
                   test = "t", effect = T, denom = "all")
aldex_ro_ri<-aldex(table_nr_ri, conditions = conds3, mc.samples = 1000, 
                   test = "t", effect = T, denom = "all")

#write.table(aldex_nr_ri, "aldex_nr_ri_funct.txt", sep = "\t")
#write.table(aldex_nr_ro, "aldex_nr_ro_funct.txt", sep = "\t")
#write.table(aldex_ro_ri, "aldex_ro_ri_funct.txt", sep = "\t")


```
Let's plot heatmap with aldex values!
```{r, message=FALSE, warning=FALSE}
#loading files
meta<-read_tsv("../Data/FINALMAP_GROUPED.txt")
table_240<- read_qza("../../Data/grouped_240_fil_noplant_nous.qza")$data %>% as.data.frame()
taxonomy_240<- read_qza("../Data/taxonomy_blast_240_0.97.qza")$data
#remove non-fungi taxa
taxonomy_filter<- taxonomy_240 %>% filter(
  !str_detect(Taxon, "ozoa"))%>% filter(
  !str_detect(Taxon, "helida")) %>% filter(
  !str_detect(Taxon, "ophyta")) %>% filter(
  !str_detect(Taxon, "Ciliophora")) %>% filter(
  !str_detect(Taxon, "Nucleariidae_and_Fonticula_group")) %>% filter(
  !str_detect(Taxon, "Arthrioida")) %>% filter(
  !str_detect(Taxon, "Labyrinthulomycetes"))  %>% filter(
  !str_detect(Taxon, "Apicomplexa")) %>% filter(
  !str_detect(Taxon, "Bicosoecida")) %>% filter(
  !str_detect(Taxon, "Breviatea")) %>% filter(
  !str_detect(Taxon, "Aphelidea"))  %>% filter(
  !str_detect(Taxon, "Arthropoda")) 

table_filter<-  table_240[match(taxonomy_filter$Feature.ID, rownames(table_240)),] %>% drop_na(.)

  
#by taxonomic levels
parse_taxa_240<- parse_taxonomy(taxonomy_filter)

summarize_taxa_240<-summarize_taxa(table_filter, parse_taxa_240)
Phylum_240<- summarize_taxa_240$Phylum 
Class_240<- summarize_taxa_240$Class
Genus_240<- summarize_taxa_240$Genus


#PHYLUM
phylum_240<- summarize_taxa_240$Phylum %>%  mutate(means = rowMeans(.)) %>%mutate_at(
  "means", as.numeric) %>%  arrange(-means)
phylum_240_abund<-data.frame( relabunda(phylum_240[1:28]) , check.names = F)

phylum_240_relab<-phylum_240_abund %>%  dplyr::select_at(
  vars(!contains("0"))) %>% dplyr::slice(
  c(1:7)) %>% rownames_to_column(var = "#OTU ID") %>% filter(
    !`#OTU ID` =="d__Eukaryota; Phragmoplastophyta") %>% dplyr::select(-means)

phylum_aldex_240<- read_tsv("../Data/aldex_results/dif_240_phylum.tsv") %>%
  rename("#OTU ID"=Feature.ID) %>% 
  right_join( phylum_240_relab)%>%dplyr::mutate_at(
    c(1),~str_extract(., "[^;]+$")) %>% column_to_rownames(var = "#OTU ID") %>% 
  mutate_at(c("kw.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05")))%>% rownames_to_column(
      var = "ids")  %>% filter(!ids == " NA") %>%  arrange(
        ids) %>% column_to_rownames(var = "ids")

heatmap<- phylum_240_relab %>% column_to_rownames(
  var = "#OTU ID")  %>% t() %>% as.data.frame() %>%  rownames_to_column(
  var = "#SampleID") %>% inner_join(meta) %>% group_by(
    Type_of_soil, Treatments) %>% summarise_if(
    is.numeric, mean) %>%  unite(
  "ids", Type_of_soil:Treatments) %>% column_to_rownames(
  var = "ids") %>%dplyr::select_at(vars(
    contains("d__")),~str_extract(
      ., "[^;]+$")) %>% t() %>% as.data.frame( ) %>% rownames_to_column(
      var = "ids")  %>% arrange(ids) %>% column_to_rownames(var = "ids")


#CLASS
class_240<- summarize_taxa_240$Class %>%  mutate(
  means = rowMeans(.)) %>%mutate_at(
  "means", as.numeric) %>%  arrange(-means)
class_240_abund<-data.frame(relabunda(class_240[1:28]) , check.names = F)
class_240_relab<-class_240_abund %>%  dplyr::select_at(
  vars(!contains("0"))) %>% dplyr::slice(
  c(1:20)) %>% rownames_to_column(
    var = "#OTU ID") %>% filter(
      !`#OTU ID` =="d__Eukaryota; Phragmoplastophyta") %>% dplyr::select(-means)

remove<- c(" Pezizomycetes", " Aconoidasida" , " Chromadorea" , 
           " Aphelidea",  " Discosea" , " Imbricatea" )

class_aldex_240<- read_tsv(
  "../Data/aldex_results/dif_240_class.tsv") %>% rename(
    "#OTU ID"=Feature.ID) %>%  right_join(
  class_240_relab)%>%dplyr::mutate_at(c(1),~str_extract(., "[^;]+$"))%>% filter(
    !`#OTU ID` == " Incertae_Sedis" & !`#OTU ID` == " NA"& !
      `#OTU ID` == " Eurotiomycetes" ) %>% arrange(
      `#OTU ID`)%>% column_to_rownames(var = "#OTU ID") %>% 
  mutate_at(c("kw.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05"))) %>% rownames_to_column(
      var = "ids")  %>% filter(!ids %in% remove) %>%  arrange(
        ids) %>% column_to_rownames(var = "ids")


heatmap_class<- class_240_relab %>% column_to_rownames(
  var = "#OTU ID")  %>% t() %>% as.data.frame(
  ) %>%  rownames_to_column(
  var = "#SampleID") %>% inner_join(meta) %>% group_by(
    Type_of_soil, Treatments) %>% summarise_if(
    is.numeric, mean) %>%  unite(
      "ids", Type_of_soil:Treatments) %>% column_to_rownames(
        var = "ids") %>%dplyr::select(
          -"d__Eukaryota; Zoopagomycota; Incertae_Sedis" , 
          -"d__Eukaryota; Mucoromycota; Incertae_Sedis") %>% dplyr::select_at(vars(
          contains("d__")),~str_extract(
            ., "[^;]+$")) %>% t() %>% as.data.frame( ) %>% rownames_to_column(
            var = "ids")  %>% filter(!ids %in% remove) %>%  arrange(
              ids) %>% filter(!ids==" Eurotiomycetes") %>% column_to_rownames(var = "ids")


#GENUS
genus_240<- summarize_taxa_240$Genus %>%  mutate(
  means = rowMeans(.)) %>%mutate_at(
  "means", as.numeric) %>%  arrange(-means)

genus_240_abund<-data.frame( relabunda(genus_240[1:28]) , check.names = F)
genus_240_relab<-genus_240_abund %>%  dplyr::select_at(vars(!contains("0"))) %>% dplyr::slice(
  c(1:27)) %>% rownames_to_column(var = "#OTU ID") %>% filter(
    !`#OTU ID` =="d__Eukaryota; Phragmoplastophyta")
remove2<- c(" Ophiostoma", " Naganishia" , " Aspergillus" , " Magnoliophyta" )

genus_aldex_240<- read_tsv("../Data/aldex_results/dif_240_genus.tsv")%>%
  rename("#OTU ID"=Feature.ID) %>%  right_join(
 genus_240_relab)%>%dplyr::mutate_at(c(1),~str_extract(., "[^;]+$"))%>% filter(
    !`#OTU ID` == " Incertae_Sedis" & !`#OTU ID` == " NA" ) %>% arrange(
      `#OTU ID`)%>% column_to_rownames(var = "#OTU ID") %>% 
  mutate_at(c("kw.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05"))) %>% rownames_to_column(
      var = "ids")  %>% filter(
        !ids %in% remove2) %>%  arrange(ids) %>% mutate(ids=case_when(
          ids ==" uncultured"  ~ " uncultured Glomerales",
          TRUE~ as.character(ids))) %>% 
  column_to_rownames(var = "ids")


heatmap_genus<- genus_240_relab %>% column_to_rownames(
  var = "#OTU ID")  %>% t() %>% as.data.frame(
) %>%  rownames_to_column(
  var = "#SampleID") %>% inner_join(meta) %>% group_by(
    Type_of_soil, Treatments) %>% summarise_if(
    is.numeric, mean) %>%  unite(
      "ids", Type_of_soil:Treatments) %>% column_to_rownames(
        var = "ids") %>%dplyr::select_at(vars(
          -ends_with("NA"))) %>% dplyr::select_at(vars(
            contains("d__")),~str_extract(
              ., "[^;]+$")) %>% t() %>% as.data.frame( ) %>% rownames_to_column(
              var = "ids")  %>% filter(
                !ids %in% remove2) %>%  arrange(ids) %>% mutate(ids=case_when(
          ids ==" uncultured"  ~ " uncultured Glomerales",
          TRUE~ as.character(ids))) %>% 
  column_to_rownames(var = "ids")

#ASV's

asv_240<- data.frame(table_filter, check.names = F)  %>%  mutate(
  means = rowMeans(.)) %>%mutate_at(
    "means", as.numeric) %>%  arrange(-means)%>% rownames_to_column(
      var = "Feature.ID")%>%  inner_join(
        taxonomy_240)%>% dplyr::select(-Consensus)

asv_240_abund<-data.frame(asv_240[c(1,30)], 
                          relabunda(asv_240[2:28]) , check.names = F) 

names<- asv_240_abund[2]



asv_aldex_240<- read.delim("../Data/aldex_results/dif_240_asv.tsv") %>% 
  rename("#OTU ID"=Feature.ID) %>% filter(
  kw.eBH < 0.05) %>%dplyr::mutate_at(c("Taxon"),~str_extract(., "[^;]+$"))%>% filter(
    !`#OTU ID` == " Incertae_Sedis" & !`#OTU ID` == " NA" ) %>% arrange(
      `#OTU ID`)%>% remove_rownames() %>% column_to_rownames(var = "#OTU ID") %>% 
  mutate_at(c("kw.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05"))) %>% rownames_to_column(
      var = "Feature.ID") %>% arrange(Taxon)  %>%drop_na(.) %>%  remove_rownames(
        )%>% column_to_rownames(var = "Taxon")


asv_240_relab<-asv_240_abund %>%  dplyr::select_at(
  vars(!contains("0"))) %>% right_join(
    asv_aldex_240, by = c("Feature.ID")) %>% dplyr::select(
      Taxon, `Non-rizospheric22`:Roots11) %>%drop_na(.) %>%  column_to_rownames(var = "Taxon")

heatmap_asv<- asv_240_relab %>% t() %>% as.data.frame(
) %>%  rownames_to_column(
  var = "#SampleID") %>% inner_join(meta) %>% group_by(Type_of_soil, Treatments) %>% summarise_if(
    is.numeric, mean) %>%  unite(
      "ids", Type_of_soil:Treatments) %>% column_to_rownames(
        var = "ids") %>% dplyr::select_at(vars(
 contains("__")),~str_extract(., "[^;]+$")) %>% t() %>% as.data.frame( 
   ) %>% rownames_to_column(var = "ids")  %>%  arrange(
     ids) %>% column_to_rownames(var = "ids")



```
Heatmap!
```{r, warning=FALSE, message=FALSE}
col_fun2 = colorRamp2(c(0,  1, 1+1e-5,10,10+1e-5,50,50+1e-5, 100), 
                      viridis(8, option = "D", direction = -1))

#pvalue annotation
mypalette<-brewer.pal(10,"BrBG")
cols_pvalue <- list('Adj. p-value' = c("<0.001" = '#AB0000',
                                  "<0.01"  =  '#FF0000',
                                "<0.05"="#EC7063",
                               ">0.05"="#F9EBEA"))
split = rep(1:3, each = 3)
treats<- c("1.Wet", "2.Dry", "3.Extreme-dry")
cols_ho<- list("Water regime" = c("1.Wet" = '#479330',
                                  "2.Dry"  =  '#FFFF00',
                                  "3.Extreme-dry"="#FF0000"))

```


```{r, fig.height=8, fig.width=10, warning=FALSE, message=FALSE}
annP = HeatmapAnnotation("Adj. p-value" = phylum_aldex_240$p.value, 
                          which = "row", col = cols_pvalue,
                         show_legend = F, gp = gpar(col = "white"), 
                         show_annotation_name = F)


ha = HeatmapAnnotation(foo = anno_block(gp = gpar(
  fill = c("#800000" ,"#808000" ,"#008000", "#D35400")), 
labels = c("Bulk soil", "Rhizosphere", "Roots"), 
labels_gp = gpar(col = "white", fontsize = 7, fontface= "bold")))



ho = HeatmapAnnotation("Water regime" = c(rep(treats, 3)),
                       which = "col", col = cols_ho,
                       annotation_name_gp = gpar(fontsize=10),
                       show_legend = T, gp = gpar(col = "white", fontize=12), 
                       show_annotation_name = T)


ht1<-Heatmap(heatmap,col = col_fun2,
             heatmap_legend_param = list(direction = "horizontal",
                                         title = "Relative \n abundance (%)",
                                         at = c(0,1, 10,  50, 100), break_dist = 1),
             rect_gp = gpar(col = "white", lwd = 1), 
             cluster_columns = F, cluster_rows = T,
             show_heatmap_legend = TRUE, top_annotation = c(ha, ho),
                           height = nrow(heatmap)*unit(6, "mm"),
             row_dend_width = unit(0.5, "cm"),right_annotation =  c(annP),
             column_order = sort(colnames(heatmap)),width = ncol(heatmap)*unit(3, "mm"), 
             column_split = split, column_title = NULL,
             row_names_gp = gpar(fontsize=12),row_title = "Phylum",
             column_title_gp = gpar(
               fill = c("#800000" ,"#808000" ,"#008000", "#D35400", "#2E4053" )))



class_aldex<- class_aldex_240 %>% drop_na(.)
annP2 = HeatmapAnnotation("Adj. p-value" = class_aldex$p.value,
                          which = "row", col = cols_pvalue,name = ".",
                          show_annotation_name = F,
                         show_legend = T, gp = gpar(col = "white"))

heat_class<- heatmap_class %>% rownames_to_column(var = "ids") %>% inner_join(
  class_aldex %>%  mutate(ids = rownames(class_aldex)), 
  by = 'ids') %>% column_to_rownames(var = "ids") %>%  dplyr::select(
    `Non-rizospheric_TC`:`Roots_TSD`)
ht2<-Heatmap(heat_class,col = col_fun2,  
             heatmap_legend_param = list(direction = "horizontal",
                                         col_fun = col_fun2, 
                                         title = "Relative \n abundance (%)",
                                         at = c(0,1, 10,  50, 100), 
                                         break_dist = 1), 
             rect_gp = gpar(col = "white", lwd = 1), 
                           height = nrow(ht1)*unit(8, "mm"),
             row_title = "Class",width = ncol(heatmap)*unit(3, "mm"),  
             row_dend_width = unit(0.5, "cm"),cluster_columns = F,
             cluster_rows = T,show_heatmap_legend = FALSE,
             row_names_gp = gpar(fontsize=12), right_annotation =  c(annP2))





annP3 = HeatmapAnnotation("Adj. p-value" = genus_aldex_240$p.value,
                          which = "row", col = cols_pvalue,name = ".",
                          show_annotation_name = F,
                          show_legend = T, gp = gpar(col = "white"))



ht3<-Heatmap(heatmap_genus,col = col_fun2,  
             heatmap_legend_param = list(direction = "horizontal",
                                         col_fun = col_fun2, 
                                         title = "Relative \n abundance (%)",
                                         at = c(0,1, 10,  50, 100),
                                         break_dist = 1), 
             rect_gp = gpar(col = "white", lwd = 1), cluster_columns = F, 
             cluster_rows = T,show_heatmap_legend = FALSE,row_title = "Genus",
                           height = nrow(ht1)*unit(9, "mm"),
             width = ncol(heatmap)*unit(1, "mm"),  
             row_dend_width = unit(0.5, "cm"),  right_annotation =  c(annP3),
             column_order = sort(colnames(heatmap_genus)), 
             row_names_gp = gpar(fontsize=12),
             column_split = split, column_title = NULL)




annP4 = HeatmapAnnotation('Adj. p-value' = asv_aldex_240$p.value,
                          which = "row", col = cols_pvalue,name = ".",
                          annotation_name_gp = gpar(fontsize=10),
                          show_legend = F, gp = gpar(col = "white"),
                          show_annotation_name = F)


ht4<-Heatmap(heatmap_asv,col = col_fun2,
             heatmap_legend_param = list(direction = "horizontal",
                                         col_fun = col_fun2, 
                                         title = "Relative \n abundance (%)",
                                         at = c(0,1, 10,  50, 100), 
                                         break_dist = 1), 
             rect_gp = gpar(col = "white", lwd = 1), row_title = "ASV's",
             cluster_columns = F, cluster_rows = T, 
             show_heatmap_legend = FALSE,row_names_gp = gpar(fontsize=12),
             width = ncol(heatmap)*unit(4, "mm"),   
              height = nrow(ht1)*unit(6, "mm"),
             row_dend_width = unit(0.5, "cm"),  right_annotation =  c(annP4),
             column_order = sort(colnames(heatmap_asv)), show_column_names = F)


#ht1%v%ht2%v%ht3%v%ht4
ht_list = ht1 %v% ht2 %v% ht3 %v% ht4

heatm<-grid.grabExpr(draw(ht_list, heatmap_legend_side = "bottom",
                          annotation_legend_side = "bottom", 
                          merge_legend=T, width = ncol(ht1)*unit(8, "mm")))

plot_grid(heatm)

```
Aldex paired plots
```{r}
#load and format files
aldex_ro_ri<- read.delim("../Data/aldex_results/dif_aldex_ro_ri.tsv",
                          ) %>% 
  mutate_at(c("diff.btw"), funs(Type = case_when(
    . < 0 ~ "Roots",
    . >  0 ~ "Rhizosphere"))) %>% arrange(diff.btw)%>%mutate(
      taxa= str_extract(Taxon, "[^_]+$"))%>% 
 mutate(taxa=case_when(
   taxa=="Sordariomycetes" ~ "c__Sordariomycetes",
   taxa=="Trichosporon" ~ "g__Trichosporon",
   taxa=="Fusarium" ~ "g__Fusarium",
   taxa=="Mucor" ~ "g__Mucor" )) %>% 
  mutate_at(c("wi.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05")))



aldex_nr_ri<- read.delim("../Data/aldex_results/dif_aldex_nr_ri.tsv" ) %>% 
  mutate_at(c("diff.btw"), funs(Type = case_when(
    . < 0 ~ "Non-rhizospheric",
    . >  0 ~ "Rhizosphere"))) %>% arrange(diff.btw)%>%mutate(
      taxa= str_extract(Taxon, "[^_]+$"))%>% 
 mutate(taxa=case_when(
   taxa=="Spizellomycetales" ~ "o__Spizellomycetales",
   taxa=="Trichosporon" ~ "g__Trichosporon",
   taxa=="Chytridiomycetes" ~ "c__Chytridiomycetes")) %>% 
  mutate_at(c("wi.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05")))


aldex_ro_nr<- read.delim("../Data/aldex_results/dif_aldex_ro_nr.tsv") %>% 
  mutate_at(c("diff.btw"), funs(Type = case_when(
    . < 0 ~ "Roots",
    . >  0 ~ "Non-rhizospheric"))) %>% arrange(diff.btw)%>%mutate(
      taxa= str_extract(Taxon, "[^_]+$"))%>% 
  mutate_at(c("wi.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05")))%>% 
  mutate_at(c("taxa"), funs(taxa = case_when(
    taxa=="herbarum" ~ "s__Cladosporium herbarum",
       taxa=="Chytridiomycetes" ~ "c__Chytridiomycetes",
       taxa=="Fusarium" ~ "g__Fusarium",
       taxa=="Spizellomycetales" ~ "o__Spizellomycetales",
       taxa=="Sordariomycetes" ~ "c__Sordariomycetes",
       taxa=="Mucor" ~ "g__Mucor" )))


cols_pvalue <- list('Adj. p-value' = c(
  "<0.001" = '#C70039', 
  "<0.01"='#FF5733',
  "<0.05"="#FFC300", 
  ">0.05"="#DAF7A6"))
effect_col_fun =colorRamp2(
  c(-3.5, 0, 3.5), 
  c("lightsalmon4", "white", "lightseagreen"))

aldex_nr_ro_funct<- read.delim("../Data/aldex_nr_ro_funct.txt" ) %>% rownames_to_column(
  var = "Taxon") %>% filter(
  wi.eBH<0.05) %>%   mutate_at(c("diff.btw"), funs(Type = case_when(
    . < 0 ~ "Non-rhizospheric",
    . >  0 ~ "Roots"))) %>% arrange(diff.btw)%>%mutate(
      taxa= str_extract(Taxon, "[^_]+$"))%>% 
  mutate_at(c("wi.eBH"), funs(p.value = case_when(
    . <= 0.001 ~ "<0.001",
    . >  0.001 & .  <= 0.01 ~ "<0.01",
    . >  0.01 & .  < 0.05 ~ "<0.05",
    . >=  0.05 ~ ">0.05")))



heat<- aldex_ro_nr %>% dplyr::select(
  taxa, "RO"= rab.win.A, "BS"= rab.win.B) 
heat1<- heat[c(-5),] %>% remove_rownames() %>% column_to_rownames(var = "taxa")
heat2<- aldex_nr_ri %>% dplyr::select(
  taxa, "BS"= rab.win.A, "R"= rab.win.B)  %>% remove_rownames() %>% column_to_rownames(var = "taxa")
heat3<- aldex_ro_ri %>% dplyr::select(
  taxa, "RO"= rab.win.A, "R"= rab.win.B)  %>% remove_rownames() %>% column_to_rownames(var = "taxa")
heat4<- aldex_nr_ro_funct %>% dplyr::select(
  taxa, "BS"= rab.win.bs, "RO"= rab.win.ro)  %>% remove_rownames() %>% column_to_rownames(var = "taxa")

```

Let's plot!
```{r}
treatment_col = structure(c("#008000", "#800000"),
                          names = c("Roots", "Non-rhizospheric"))

barpl = rowAnnotation("difference \nbetween groups" = anno_barplot(
  aldex_ro_nr[c(-5),]$diff.btw, which = "row",
  gp = gpar(fill = treatment_col[aldex_ro_nr[c(-5),]$Type]),
  width = unit(3, "cm")),  show_annotation_name = F,
  annotation_name_gp =gpar(fontsize = 0),
  annotation_name_rot = 0)

annP = HeatmapAnnotation("Adj. p-value" =aldex_ro_nr[c(-5),]$p.value, 
                         simple_anno_size = unit(0.35, "cm"),
                         annotation_name_gp =gpar(fontsize = 7),
                         which = 'row',
                         annotation_legend_param = list(
                           title_gp = gpar(fontsize = 9, fontface="bold"),
                           labels_gp = gpar(fontsize = 9),
                           direction ="vertical"),
                         col = cols_pvalue,
                        show_legend = F, gp = gpar(col = "white"), 
                        show_annotation_name = T)

annE = rowAnnotation("Effect size" = aldex_ro_nr[c(-5),]$effect, 
                     annotation_name_gp =gpar(fontsize = 9),
                     col = list("Effect size" = effect_col_fun),
                     simple_anno_size = unit(0.35, "cm"),
                     annotation_legend_param = list(title_gp = gpar(fontsize = 9, 
                                                                    fontface="bold"),
                                                    labels_gp = gpar(fontsize = 9),
                                                    direction ="vertical"),
                     show_legend = F, gp = gpar(col = "white"), show_annotation_name = T)





H1<-Heatmap(heat1, cluster_rows = F,
            cluster_columns = F,  width = ncol(heat1)*unit(8, "mm"), 
            height = nrow(heat1)*unit(7.7, "mm"),column_names_rot = 0,
            left_annotation = c(annE, annP),
            right_annotation=c(barpl),
            name = "Median \n clr value", 
            heatmap_legend_param = list(direction = "vertical" , 
                                        labels_gp = gpar(fontsize = 7),
                                        title_gp = gpar(fontsize = 9,  fontface="bold"),
                                        legend_height = unit(1.4, "cm")), 
            column_names_gp = gpar(fontsize = 9),
            row_names_gp = gpar(fontsize = 12), show_heatmap_legend = T)


H1.1<- draw(H1,  heatmap_legend_side = "right")

H1.1
#heat2

treatment_col = structure(c("#808000", "#800000"),
                          names = c("Rhizosphere", "Non-rhizospheric"))
barpl = rowAnnotation("difference \nbetween groups" = anno_barplot(
  aldex_nr_ri$diff.btw,
  gp = gpar(fill = treatment_col[aldex_nr_ri$Type]),
  width = unit(3, "cm"),   height = unit(2, "cm")),
  show_annotation_name = F,annotation_name_gp =gpar(fontsize = 9),
  annotation_name_rot = 0)

annP = rowAnnotation("Adj. p-value" = aldex_nr_ri$p.value, 
                     simple_anno_size = unit(0.35, "cm"),
                     col = cols_pvalue,
                     annotation_name_gp =gpar(fontsize = 9),
                     show_legend = F, gp = gpar(col = "white"), 
                     show_annotation_name = T)

annE = rowAnnotation("Effect size" = aldex_nr_ri$effect, 
                     simple_anno_size = unit(0.35, "cm"),
                     col = list("Effect size" = effect_col_fun),
                     annotation_name_gp =gpar(fontsize = 9),
                     show_legend = F, gp = gpar(col = "white"),
                     show_annotation_name = T)




H2<-Heatmap(heat2, cluster_rows = F, cluster_columns = F, 
            width = ncol(heat)*unit(6, "mm"), 
            height = nrow(heat)*unit(5, "mm"),column_names_rot = 0,
            left_annotation = c(annE, annP),
            right_annotation = barpl,
            name = "Median \n clr value", 
            heatmap_legend_param = list(direction = "vertical" , 
                                        labels_gp = gpar(fontsize = 7),
                                        title_gp = gpar(fontsize = 9, 
                                                        fontface="bold"),
                                        legend_height = unit(1.4, "cm")), 
            column_names_gp = gpar(fontsize = 9),
            row_names_gp = gpar(fontsize = 12))

H2.1<- draw(H2, heatmap_legend_side = "right")
H2.1



#heat3

treatment_col = structure(c("#008000", "#808000"), 
                          names = c("Roots", "Rhizosphere"))
barpl = rowAnnotation("difference \nbetween groups" = anno_barplot(
  aldex_ro_ri$diff.btw, 
  gp = gpar(fill = treatment_col[aldex_ro_ri$Type]),
  width = unit(3.5, "cm"),   height = unit(2, "cm")),
  show_annotation_name = F,
  annotation_name_gp =gpar(fontsize = 9),   
  annotation_name_rot = 0)

annP = rowAnnotation("Adj. p-value" = aldex_ro_ri$p.value, 
                     annotation_name_gp =gpar(fontsize = 9),
                     simple_anno_size = unit(0.35, "cm"),
                     annotation_legend_param = list(title_gp = gpar(fontsize = 9, 
                                                    fontface="bold"),
                                                    labels_gp = gpar(fontsize = 9),
                                                    direction ="horizontal"),
                     col = cols_pvalue,show_legend = T, 
                     gp = gpar(col = "white"), show_annotation_name = T)

annE = rowAnnotation("Effect size" = aldex_ro_ri$effect, 
                     annotation_name_gp =gpar(fontsize = 9),
                     col = list("Effect size" = effect_col_fun),
                     simple_anno_size = unit(0.35, "cm"),
                     annotation_legend_param = list(title_gp = gpar(fontsize = 9, 
                                                                    fontface="bold"),
                                                    labels_gp = gpar(fontsize = 9),
                                                    direction ="horizontal"),
                     show_legend = T, gp = gpar(col = "white"), show_annotation_name = T)




H3<-Heatmap(heat3, cluster_rows = F, cluster_columns = F, 
            width = ncol(heat)*unit(5, "mm"), 
            height = nrow(heat)*unit(4.5, "mm"),column_names_rot = 0,
            left_annotation = c(annE, annP), name = "Median \n clr value",
            right_annotation = barpl,
            heatmap_legend_param = list(direction = "vertical" , labels_gp = gpar(fontsize = 7),
                                        title_gp = gpar(fontsize = 9,  fontface="bold"),
                                        legend_height = unit(1.4, "cm")), 
            column_names_gp = gpar(fontsize = 9),
            row_names_gp = gpar(fontsize = 12)) %v% NULL
H3.1<- draw(H3, annotation_legend_side = "top", heatmap_legend_side="right")
H3.1


#heat4
#heatmap funciones
cols_pvalue <- list('Adj. p-value' = c("<0.001" = '#AB0000',
                                  "<0.01"  =  '#FF0000',
                                "<0.05"="#EC7063",
                               ">0.05"="#F9EBEA"))

treatment_col = structure(c("#008000", "#800000"),
                          names = c("Roots", "Non-rhizospheric"))
barpl = rowAnnotation("difference \nbetween groups" = anno_barplot(
  aldex_nr_ro_funct$diff.btw, 
  gp = gpar(fill = treatment_col[aldex_nr_ro_funct$Type]),
  width = unit(4, "cm"),   height = unit(2, "cm")),
show_annotation_name = F,
  annotation_name_gp =gpar(fontsize = 8),   
  annotation_name_rot = 0)

annP = rowAnnotation('Adj. p-value' = aldex_nr_ro_funct$p.value, 
                     annotation_name_gp =gpar(fontsize = 9),
                     simple_anno_size = unit(0.35, "cm"),
                     annotation_legend_param = list(title_gp = gpar(fontsize = 9, 
                                                    fontface="bold"),
                                                    labels_gp = gpar(fontsize = 9),
                                                    direction ="vertical"),
                     col = cols_pvalue,show_legend = T, 
                     gp = gpar(col = "white"), show_annotation_name = T)

annE = rowAnnotation("Effect size" = aldex_nr_ro_funct$effect, 
                     annotation_name_gp =gpar(fontsize = 9),
                     col = list("Effect size" = effect_col_fun),
                     simple_anno_size = unit(0.35, "cm"),
                     annotation_legend_param = list(title_gp = gpar(fontsize = 9, 
                                                                    fontface="bold"),
                                                    labels_gp = gpar(fontsize = 9),
                                                    direction ="horizontal"),
                     show_legend = T, gp = gpar(col = "white"), show_annotation_name = T)




H4<-Heatmap(heat4, cluster_rows = F, cluster_columns = F,  width = ncol(heat)*unit(10, "mm"), 
            height = nrow(heat)*unit(6, "mm"),column_names_rot = 0,
            left_annotation = c(annE, annP), name = "Median \n clr value",
            right_annotation = barpl,
            heatmap_legend_param = list(direction = "horizontal" , labels_gp = gpar(fontsize = 7),
                                        title_gp = gpar(fontsize = 7,  fontface="bold"),
                                        legend_height = unit(1.4, "cm")), 
            column_names_gp = gpar(fontsize = 9),
            row_names_gp = gpar(fontsize = 12)) %v% NULL
H4.1<- draw(H4, annotation_legend_side = "top", heatmap_legend_side="bottom")
H4.1


aldex_H1<- grid.grabExpr(draw(H1.1))
aldex_H2<- grid.grabExpr(draw(H2.1))
aldex_H3<- grid.grabExpr(draw(H3.1))
aldex_H4<- grid.grabExpr(draw(H4.1))


paired_grouped<-plot_grid(aldex_H3, aldex_H1, aldex_H2, nrow =  3,
                          rel_heights = c(1.1, 1, 1),
                          labels = c("B", "C", "D"))+ theme(
                            plot.margin = unit(c(0, 0, 0, 0), "cm"))

```



```{r, fig.height=9.5, fig.width=14}


c<-cowplot::plot_grid(heatm ,paired_grouped,  ncol = 2,  rel_widths = c(1.8,1.4), labels = c("A", NULL),  align ="h", axis = "bt" , label_size = 18)
c
#ggsave('../../Figures_final/Fig4.compartments_treatment_filt_nobarplot.pdf',
 #   width = 12.5, height = 9, dpi = 300, plot =c)
#ggsave('../../Figures_final/FigSX.Aldex_functional_mod.pdf',
  #   width = 10, height = 6, dpi = 300, plot =aldex_H4)
```

