---
title: "Correlations and glomus abundances"
author: 
- name: Stephanie Hereira
  affiliation: Centro de Investigación y estudios avanzados del IPN
  email: shereirap@cinvestav.mx
date: "`r format(Sys.time(), '%d - %m - %Y')`"
output:
  html_document:
    theme: united
    highlight: tango
    toc: yes
    toc_depth: 2
    toc_float: yes
---

```{r, warning=FALSE, message=FALSE}
#ARBUSCULES IMAGE
library(imager)
library(cowplot)
library(viridis)
library(tidyverse)
library(ggpubr)
library(tidyverse)
library(qiime2R)
library(circlize)
library(viridis)
library(ggpubr)
library(ComplexHeatmap)
```

```{r, warning=FALSE, message=FALSE}
metadata2<- read_tsv("../Data/meta_dos.txt")
otutable<- read_qza("../../Data/merge_table_240_noplant_filtered_nous.qza")$data
taxonomy<- read_qza("../Data/taxonomy_blast_240_0.97.qza")$data

parse<- qiime2R::parse_taxonomy(taxonomy)
phyl<- qiime2R::summarize_taxa(features = otutable, taxonomy = parse)$Genus
phy.ra <- function(x){(t(x)/colSums(x))}

phyl_ro<- phyl %>% dplyr::select_at(vars(contains("RO"))) %>% filter_all(
  ., any_vars(. != 0)) %>%   phy.ra(
  .) %>% as.data.frame() %>% rownames_to_column(var = "SampleID")

phy_met<- phyl_ro %>% inner_join(metadata2) %>% column_to_rownames(var = "SampleID") %>% dplyr::select(
  contains("d__"), hojas, raices, Arbus_per)

library(Hmisc)
cors<- phy_met
corr <- rcorr(as.matrix(cors), type=c("spearman"))
#print(corr)
cor.out <-corr$r
#write.table (cor.out, "yenCorrgen", sep="\t")

cor.plot<- cor.out %>% as.data.frame() %>% dplyr::select(Arbus_per) %>% filter(abs(Arbus_per)>=abs(0.4))

cor_heat<-cor.plot%>% rownames_to_column(var="id") %>%  mutate_at(
  "id", str_replace, "; NA", "")%>%  mutate_at(
  "id", str_replace, "; NA", "")%>%  mutate_at(
  "id", str_replace, "; NA", "")%>% mutate( tax= str_extract(id, "[^; ]+$")) %>% mutate(
    tax= case_when(
      tax=="raices"~ "Phenolic root content",
      TRUE~as.character(tax))) %>% filter(!id=="Arbus_per") %>% 
  dplyr::select(tax, "%Arbuscule \n colonization"=Arbus_per) %>% 
  column_to_rownames(var = "tax")



test_labels<- cor_heat[1]

my_palette <- colorRampPalette(c("red", "white","blue"))(n=599)
library(pheatmap)
heats<-pheatmap(cor_heat, color = my_palette,legend = TRUE,cellheight = 50,
        cellwidth = 40,border_color = "black",
         cluster_cols = F, cluster_rows = F, fontsize = 10)

heat<- grid.grabExpr(heats)

```


```{r}
otu_grouped<- read.delim("/home/steph/Documents/Documentos/fastas nuevos/18S/demultiplexed/demux/table_grouped_noplant_filt_nous/table_grouped.tsv",
skip = 1, check.names = F) %>% column_to_rownames(var = "#OTU ID") %>% dplyr::select(-taxonomy)

taxo<- read_qza("/home/steph/Documents/Documentos/fastas nuevos/18S//demultiplexed/demux/seqs_and_taxonomy/taxonomy_blast_240_0.97.qza")$data
phyra<-t(otu_grouped)/colSums(otu_grouped) *100

metadata<- read_tsv("/home/steph/Documents/Documentos/fastas nuevos/18S//MAPPINGS/FINALMAP_GROUPED.txt")

otu_grouped_relab<- phyra %>% t() %>% as.data.frame() %>% rownames_to_column(
  var = "Feature.ID") %>% inner_join(taxonomy) %>% dplyr::select(-Feature.ID, -Consensus)


otu_glom<-otu_grouped_relab %>% 
  filter(str_detect(Taxon, 'Glom')) %>% rownames_to_column(var = "rows") %>% unite(
    names, c(rows, Taxon), sep = "_"  ) %>% column_to_rownames(
      var = "names") %>% t() %>% as.data.frame(
        ) %>% rownames_to_column(var = "#SampleID") %>% inner_join(metadata)
rel<-otu_glom %>% group_by(Type_of_soil, Treatments) %>% summarise_if(
  is.numeric, mean) %>% dplyr::select(
    Type_of_soil,Treatments,contains("d__")) %>% unite(
    "ids", Type_of_soil:Treatments) %>% column_to_rownames(var = "ids") %>% 
  t() %>% as.data.frame() %>% rownames_to_column(var = "taxa") %>% mutate( 
    tax= str_extract(taxa, "[^__]+$")) %>% mutate(
   taxon = case_when(
 tax=="sp."~"s__Glomeromycotina",
tax=="uncultured"~"g__uncultured Glomerales",
tax=="Glomeraceae"~"f__Glomeraceae",
tax=="Rhizophagus"~"g__Rhizophagus",
tax=="Glomeromycetes"~"c__Glomeromycetes",
      TRUE ~ as.character(tax))) %>% filter(!taxon=="Plectosphaerellaceae")

relab<-otu_glom %>% dplyr::select("#SampleID",contains("d__")) %>% column_to_rownames(
  var = "#SampleID") %>% 
  t() %>% as.data.frame() %>% rownames_to_column(var = "taxa") %>% mutate(
    tax= str_extract(
    taxa, "[^__]+$")) %>% mutate(
    taxon = case_when(
 tax=="sp."~"s__Glomeromycotina",
tax=="uncultured"~"g__uncultured Glomerales",
tax=="Glomeraceae"~"f__Glomeraceae",
tax=="Rhizophagus"~"g__Rhizophagus",
tax=="Glomeromycetes"~"c__Glomeromycetes",
      TRUE ~ as.character(tax))) %>% filter(
        !taxon=="Plectosphaerellaceae")
rel_sum<- rel %>% group_by(taxon) %>% summarise_if(
  is.numeric, sum) %>% column_to_rownames(
  var = "taxon") 


target <- c("f__Glomeraceae","c__Glomeromycetes",
            "g__Rhizophagus" ,"g__uncultured Glomerales","s__Glomeromycotina")
rel_sum2<-rel_sum %>%rownames_to_column(var = "name") %>% arrange(
  factor(name, levels = target)) %>% column_to_rownames(var = "name")

#other heatmap
col_fun2 = colorRamp2(c(0, 0.5, 0.5+1e-5, 1,1.5), viridis(5, option = "D", direction = -1))
split = rep(1:3, each = 3)
treats<- c("1.Wet", "2.Dry", "3.Extreme-dry")
cols_ho<- list("Water regime" = c("1.Wet" = '#479330',
                               "2.Dry"  =  '#FFFF00',
                               "3.Extreme-dry"="#FF0000"))
ha = HeatmapAnnotation(foo = anno_block(gp = gpar(
  fill = c("#800000" ,"#808000" ,"#008000", "#D35400")), 
  labels = c("Bulk soil", "Rhizosphere", "Roots"), 
  labels_gp = gpar(col = "white", fontsize = 7, fontface= "bold")))

ho = HeatmapAnnotation("Water regime" = c(rep(treats, 3)),
                       which = "col", col = cols_ho,
                       annotation_name_gp = gpar(fontsize=10),
                       show_legend = T, gp = gpar(col = "white", 
                                                  fontize=12), 
                       show_annotation_name = T)

ht<-Heatmap(rel_sum2, col = col_fun2,
            heatmap_legend_param = list(direction = "horizontal",
                 col_fun = col_fun2, title = "Relative \n abundance (%)",
                 at = c(0,0.5, 1, 1.5), break_dist = 1), rect_gp = gpar(col = "white", lwd = 1), 
            top_annotation = c(ha, ho),column_split = split,
           cluster_columns = F, cluster_rows = F,show_heatmap_legend = TRUE, 
         show_column_names = FALSE,
           width = ncol(rel_sum2)*unit(10, "mm"), 
           height = nrow(rel_sum2)*unit(12, "mm"),
           column_title = NULL,row_names_gp = gpar(fontsize=10))+ 
  guides(fill=guide_legend(title="Water regime"))

abund<-draw(ht, heatmap_legend_side = "top", annotation_legend_side = "top")
abunds<- grid.grabExpr(draw(abund))

```

```{r}

one<-plot_grid(abunds, heat, rel_widths = c(1.5,1), labels = c("A", "B"))
```

```{r}
#ggsave('../../Figures_final/Fig3.cor_glomus.pdf',
#"     width = 10, height = 6, dpi = 300, plot =one)

```

